### ISSUE TITLE
Inappropriate,

### ISSUE THREAD

**Issue by tox123** [Theofilos-Chamalis/edX-6.00.1x-Introduction-to-Computer-Science-and-Programming#2]
isn't this a violation of the honor code, no offence, but wasn't there a rule about **_not**_ doing this or something?

**Comment by Theofilos-Chamalis** [comment]
On 26/7/2014 10:46 μμ, SBcloatitr wrote:

> isn't this a violation of the honor code, no offence, but wasn't there 
> a rule about _/not/_ doing this or something?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Theo-Chamalis/edX-6.00.1x-Introduction-to-Computer-Science-and-Programming/issues/2.
> 
> Indeed there was but it stated of not posting code online while taking 
> the course. It has been many months since then and some coding exercises 
> might have changed, but aside from that I do _NOT_ encourage people to 
> blindly copy and paste it but read it thoroughly and understand it. I 
> have also answered to many mails about questions regarding python coding 
> and I am here to help if you need to.

Best regards
Theofilos
