### ISSUE TITLE
It could be very useful to read your code after submitting 

### ISSUE THREAD

**Issue by BattleWoLFz99** [Theofilos-Chamalis/edX-6.00.1x-Introduction-to-Computer-Science-and-Programming#3]
Whether you are new to python or not at that time, I gained a lot from your code! Like Hangman Part 1, I almost wrote down 10 line on it= = Good job!

**Comment by sepandasadi** [comment]
Thank you BatteWoLFz99, glad it was helpful. And I was actually new by the time I was working on this course. cheers,
